slug = "obsessive-journaler"
title = "Obsessive Journaler"
author = "Nik"
value = 15
description = """The FBI finally caught up to an elusive suspect known for their weird, technology-based publicity stunts. When arresting him, they were just able to get a memory dump from his ancient machine before it crashed. They've turned [the file](https://drive.google.com/file/d/1A0nuI4oojmaHILWoGdUcMFeAoDIlyedQ/view?usp=sharing) over to you for some forensic work. Be sure to decompress it before getting started!

The suspect was known to keep an extensive collection of journals with hidden messages; he had to be working on one something when he was caught. What was he trying to say?"""
tags = [ "memory" ]
files = []
flag = "flag{helpless}"
enabled = true