slug = "hashing-things-out"
title = "Hashing Things Out"
author = "Salma"
value = 15
description = """If you’ve solved ‘Txting and Driving’, you should’ve come across a password protected folder. I wonder if the NTLM hash of the account I’m logged in with can help you get in? Here is the [memory dump](https://drive.google.com/drive/u/1/folders/1rZ_fhLA3Py2uZ0G6gWeFp9m2c6y_a6Zl)  (Note: Memory dump is the same for all my challenges)"""
tags = ["memory"]
files = []
flag = "flag{h4sht4gs_4r3_gr34t}"
enabled = true
