slug = "magic-8-ball"
title = "Magic 8 Ball"
author = "Laura"
value = 15
description = """I tried using [a magic 8 ball](magic8ball.pcapng) to find the flag, but all it said was to “Concentrate and look again.” The only problem is, I don’t know where to look. Can you help me? (Note: Flag does not contain spaces)"""
tags = ["pcap"]
files = ["magic8ball.pcapng"]
flag = "flag{just_hacked_google}"
enabled = true
