slug = "avatar"
title = "Avatar"
author = "Jerry"
value = 15
description = """Water. Earth. Fire. Air. Long ago, the four nations lived together in harmony. Then, everything changed when the Fire Nation attacked. Only the Avatar, master of all four elements, could stop them, but when the world needed him most, he vanished, only leaving this [image](avatar.png)."""
tags = ["file"]
files = ["avatar.png"]
flag = "flag{live_action_cast_hyyype}"
enabled = true
