slug = "gotta-catch-them-all"
title = "Gotta Catch Them All"
author = "Laura"
value = 10
description = "I want to be the greatest Pokemon master of them all, but I’m having some difficulty catching those flags. Good thing we have some spare master balls on hand! Can you find the flag hidden in these packets?"
tags = ["pcap"]
files = ["pokemon.pcapng"]
flag = "flag{pikachu_loves_ketchup}"
enabled = true
