slug = "txting-and-driving"
title = "Txting and Driving"
author = "Salma"
value = 10
description = """I’ve got some pretty important stuff in this super secret google drive folder! Sure hope I remembered to switch to incognito before looking it up… (PS: Solve this before my other challenges, you may need it in the future) Here is the [memory dump](https://drive.google.com/drive/u/1/folders/1rZ_fhLA3Py2uZ0G6gWeFp9m2c6y_a6Zl)  (Note: Memory dump is the same for all my challenges)"""
tags = ["memory"]
files = []
flag = "flag{drivers_license}"
enabled = true
