id = 6
title = "Cyber Academy: Smart Contract"
short = "Smart Contract" 
date = "Thursday 2/17 6:00PM-8:00PM PT"
description = """Crypto currencies are everywhere these days, but have you ever wondered how they work? Join our workshop to find out about how smart contracts automate the exchange of crypto currencies! By the end, you might even learn enough to make the next 🐶 Dogecoin!

zoom link: https://ucla.zoom.us/j/95081428653?pwd=am9rb2JuK25LVmFMT3NxaHJyV3J6Zz09
"""
link = ""
slides = ""
