slug = "into-the-spiderverse"
title = "Into the Spiderverse"
author = "Laura"
value = 10
description = "Uh oh! The space-time continuum was accidentally disrupted, and now there’s a bunch of spider people swinging around Brooklyn. They all seem to follow a certain protocol… Can you use your spidey senses and find all of the spiderpeople? (Format: flag{name1_name2_name3}; enter names as written in order from top to bottom)"
tags = ["pcap"]
files = ["spiderverse.pcapng"]
flag = "flag{PeterParker_GwenStacy_MilesMorales}"
enabled = true
