slug = "i-heart-crochet"
title = "I Heart Crochet"
author = "Caolinn"
value = 10
description = """Get out your crochet needles and [yarn](iReallyHeartCrochet.jpg) to make something for your evil grandkids so that you don't get sent to a retirement home! If a sweater doesnt convince them, try guilt!! """
tags = ["file"]
files = ["iReallyHeartCrochet.jpg"]
flag = "flag{NotJustGrandmasUseStrings}"
enabled = true
