slug = "take-note"
title = "Take Note"
author = "Salma"
value = 10
description = """I sure have a lot of files open, I wonder if any of them contain some text that might command my attention? Here is the [memory dump](https://drive.google.com/drive/u/1/folders/1rZ_fhLA3Py2uZ0G6gWeFp9m2c6y_a6Zl)  (Note: Memory dump is the same for all my challenges)"""
tags = ["memory"]
files = []
flag = "flag{theres_waldo}"
enabled = true
